### PR TITLE
Fix #6 by using utf16 over ISO-8859-1

### LINKED ISSUE #6: Japanese characters
When trying to save the following names on the `Artist` tag of a file, broken characters appear.
Strings I'm trying to save:
```
分島花音
ナノ
```

Both get converted to, respectively:
```
ö±ó
ÊÎ
```

When trying to save the following string to the `Title` tag, same thing happens:
```
Dark Night Rhapsody～明けない夜の狂詩曲
```
This is being saved as: 
```
Dark Night Rhapsody^QjDnÂiò
```

Any ideas?

### PR DESCRIPTION
**Pull request by SwadicalRag**
Fixes #6

### CODE REVIEW

**Comment by egoroof** [comment]
Look at this (from my id3 writer):
```js
function encodeUtf16le(str) {
    const codePoints = String(str).split('').map((c) => c.charCodeAt(0));
    const output = new Uint8Array(str.length * 2);
    new Uint16Array(output.buffer).set(codePoints);
    return output;
}
```
enjoy :)

**Comment by Zazama** [comment]
Hi, 
thanks for the pull request. 
I also added an iconv-lite decode call to the read function. I think it's the best to keep iconv-lite for better compatibility.

**Comment by SwadicalRag** [comment]
sweet, sounds good, now back to scraping weeb songs



#### P.S. are you able to bump the version and update this on npm too, @Zazama?

**Comment by Zazama** [comment]
Should already be updated to 0.0.8 :P

**Pull request merged**
